"""Add pprice column to prodInventory table

Revision ID: 40aa7047decd
Revises: 
Create Date: 2024-06-25 01:06:07.960056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40aa7047decd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pprice', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod_inventory', schema=None) as batch_op:
        batch_op.drop_column('pprice')

    # ### end Alembic commands ###
